# Generated by Django 4.2.2 on 2023-06-24 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('oldest_data', models.DateField(default=datetime.date(9999, 12, 31))),
                ('newest_data', models.DateField(default=datetime.date(1, 1, 1))),
                ('lat_min', models.FloatField(null=True)),
                ('lat_max', models.FloatField(null=True)),
                ('lat_count', models.IntegerField(default=0)),
                ('lon_min', models.FloatField(null=True)),
                ('lon_max', models.FloatField(null=True)),
                ('lon_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoJSONFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date(9999, 12, 31))),
                ('file', models.FileField(upload_to='')),
                ('data', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='projectApp.country')),
            ],
        ),
    ]
