# Generated by Django 4.2 on 2023-04-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentinel5PData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40)),
                ('filename', models.CharField(max_length=90)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Scanline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sentinel_5p_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.sentinel5pdata')),
            ],
        ),
        migrations.CreateModel(
            name='CoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.scanline')),
            ],
        ),
    ]
