# Generated by Django 4.2.2 on 2023-06-23 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('oldest_data', models.DateField(default=datetime.date(9999, 12, 31))),
                ('newest_data', models.DateField(default=datetime.date(1, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Sentinel5PData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=90, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('min_latitude', models.FloatField(default=float("nan"))),
                ('max_latitude', models.FloatField(default=float("nan"))),
                ('min_longitude', models.FloatField(default=float("nan"))),
                ('max_longitude', models.FloatField(default=float("nan"))),
                ('fully_imported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scanline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sentinel_5p_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanlines', to='projectApp.sentinel5pdata')),
            ],
        ),
        migrations.CreateModel(
            name='GeoJSONFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date(9999, 12, 31))),
                ('file', models.FileField(upload_to='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='projectApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='CoValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=float("nan"))),
                ('longitude', models.FloatField(default=float("nan"))),
                ('co_value', models.FloatField(blank=True, null=True)),
                ('scanline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_values', to='projectApp.scanline')),
            ],
        ),
    ]
