# Generated by Django 4.2 on 2023-04-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codata',
            name='co_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codata',
            name='latitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='codata',
            name='longitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='max_latitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='max_longitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='min_latitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='min_longitude',
            field=models.FloatField(default=float("nan")),
        ),
    ]
