# Generated by Django 4.2 on 2023-04-22 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_alter_codata_co_value_alter_codata_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=float("nan"))),
                ('longitude', models.FloatField(default=float("nan"))),
                ('co_value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scanline',
            name='sentinel_5p_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanlines', to='projectApp.sentinel5pdata'),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='max_latitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='max_longitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='min_latitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='min_longitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.DeleteModel(
            name='CoData',
        ),
        migrations.AddField(
            model_name='covalue',
            name='scanline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_values', to='projectApp.scanline'),
        ),
    ]
