# Generated by Django 4.2 on 2023-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_alter_covalue_latitude_alter_covalue_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covalue',
            name='latitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='covalue',
            name='longitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='max_latitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='max_longitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='min_latitude',
            field=models.FloatField(default=float("nan")),
        ),
        migrations.AlterField(
            model_name='sentinel5pdata',
            name='min_longitude',
            field=models.FloatField(default=float("nan")),
        ),
    ]
